// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihtqfagbdlpgymfoxqgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodHFmYWdiZGxwZ3ltZm94cWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTY4NDEsImV4cCI6MjA2MDY3Mjg0MX0.kkSemWiFAYXiFWOjVAz20KvGNgtSrzvej91Pc0-K2BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);